### ISSUE TITLE
Ticking entity crash with Straw Hat

### ISSUE THREAD

**Issue by CaptainPepperjack** [0rc1nus/Overweight-Farming#46]
Crash report: 
[crash-2022-10-13_22.25.11-server.txt](https://github.com/0rc1nus/Overweight-Farming/files/9781967/crash-2022-10-13_22.25.11-server.txt)
https://paste.ee/p/w5NHl

Minecraft 1.18.2
overweightfarming-1.18.2-1.6.0-forge
Forge: 40.1.80

I reproduced it again in a brand new world by simply putting on a straw hat. Here's that crash report:

[crash-2022-10-13_22.58.34-server.txt](https://github.com/0rc1nus/Overweight-Farming/files/9782097/crash-2022-10-13_22.58.34-server.txt)
https://paste.ee/p/uXYJX

and reproducted it without any oculus/shaders: 
[crash-2022-10-14_19.23.51-server.txt](https://github.com/0rc1nus/Overweight-Farming/files/9790700/crash-2022-10-14_19.23.51-server.txt)

**Comment by drakray** [comment]
I got the same crash by putting the hat on, https://pastebin.com/Q6UihurX
Minecraft 1.18.2
Forge 40.1.92
OWF 1.6.0
Bunch of other mods listed in the crashLog

<details><summary>crash snippet</summary>

```
Description: Ticking player

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=berries, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at net.orcinus.overweightfarming.events.MobEvents.onLivingUpdate(MobEvents.java:130) ~[overweightfarming-1.18.2-1.6.0-forge.jar%23170!/:1.18.2-1.6.0-forge] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_194_MobEvents_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:301) ~[forge-1.18.2-40.1.80-universal.jar%23228!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:galosphere.mixins.json:LivingEntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:wildbackport-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wildbackport-common.mixins.json:common.PlayerMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinPlayerEntity,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/enigmaticgraves/enigmaticgraves.mixins.json:PlayerEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

```
</details>

**Comment by drakray** [comment]
Adding Hedgehog to my pack fixes the crash
Seems to be missing a condition around https://github.com/0rc1nus/Overweight-Farming/blob/main/src/main/java/net/orcinus/overweightfarming/events/MobEvents.java line 130, as `kiwiVines` return AIR if hedgehog is missing?

**Comment by dabutant** [comment]
This issue still persists, any fixes? Happened as soon as I put on a straw hat. I get the same crash report as drakray.

**Comment by Banh-Bao** [comment]
This issues continues into the 1.19 ver of the mod. 
https://pastebin.com/ErPbz6rD

**Comment by cock1234567** [comment]
Any fixes?
